services:
  checkmate-db:
    image: mysql:8.0
    container_name: checkmate-db
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - checkmate-mysql:/var/lib/mysql
    networks:
      - checkmate-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u root -proot_password || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  checkmate-redis:
    image: redis:7.2-alpine
    container_name: checkmate-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - checkmate-redis:/data
    networks:
      - checkmate-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db_seeder:
    image: mysql:8.0
    container_name: db-seeder
    depends_on:
      checkmate-db:
        condition: service_healthy
    networks:
      - checkmate-network
    volumes:
      - ./seedData.sql:/seedData.sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    entrypoint: >
      sh -c "sleep 10 &&
      mysql --host=checkmate-db --user=root --password=root_password < ./seedData.sql &&
      echo 'Database seeding completed' &&
      exit"

  checkmate-app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: checkmate-app
    depends_on:
      checkmate-db:
        condition: service_healthy
      checkmate-redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: ${DOCKER_DB_URL}
      REDIS_URL: redis://checkmate-redis:6379
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - checkmate-network
    command: >
      sh -c "yarn start"

volumes:
  checkmate-mysql:
    name: checkmate-db
  checkmate-app:
    name: checkmate-app
  checkmate-redis:
    name: checkmate-redis

networks:
  checkmate-network:
    driver: bridge
